#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="XPX")]
	public partial class baseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDetalle_producto(Detalle_producto instance);
    partial void UpdateDetalle_producto(Detalle_producto instance);
    partial void DeleteDetalle_producto(Detalle_producto instance);
    partial void InsertEquipo(Equipo instance);
    partial void UpdateEquipo(Equipo instance);
    partial void DeleteEquipo(Equipo instance);
    partial void InsertFactura(Factura instance);
    partial void UpdateFactura(Factura instance);
    partial void DeleteFactura(Factura instance);
    partial void InsertFactura_compra(Factura_compra instance);
    partial void UpdateFactura_compra(Factura_compra instance);
    partial void DeleteFactura_compra(Factura_compra instance);
    partial void InsertIngreso(Ingreso instance);
    partial void UpdateIngreso(Ingreso instance);
    partial void DeleteIngreso(Ingreso instance);
    partial void InsertPieza(Pieza instance);
    partial void UpdatePieza(Pieza instance);
    partial void DeletePieza(Pieza instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertTrabajo(Trabajo instance);
    partial void UpdateTrabajo(Trabajo instance);
    partial void DeleteTrabajo(Trabajo instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public baseDataContext() : 
				base(global::Datos.Properties.Settings.Default.XPXConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public baseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public baseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_producto> Detalle_producto
		{
			get
			{
				return this.GetTable<Detalle_producto>();
			}
		}
		
		public System.Data.Linq.Table<Equipo> Equipo
		{
			get
			{
				return this.GetTable<Equipo>();
			}
		}
		
		public System.Data.Linq.Table<Factura> Factura
		{
			get
			{
				return this.GetTable<Factura>();
			}
		}
		
		public System.Data.Linq.Table<Factura_compra> Factura_compra
		{
			get
			{
				return this.GetTable<Factura_compra>();
			}
		}
		
		public System.Data.Linq.Table<Ingreso> Ingreso
		{
			get
			{
				return this.GetTable<Ingreso>();
			}
		}
		
		public System.Data.Linq.Table<Pieza> Pieza
		{
			get
			{
				return this.GetTable<Pieza>();
			}
		}
		
		public System.Data.Linq.Table<Pieza_usada> Pieza_usada
		{
			get
			{
				return this.GetTable<Pieza_usada>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Trabajo> Trabajo
		{
			get
			{
				return this.GetTable<Trabajo>();
			}
		}
		
		public System.Data.Linq.Table<Trabajo_realizado> Trabajo_realizado
		{
			get
			{
				return this.GetTable<Trabajo_realizado>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cli_cedula;
		
		private string _cli_nombre;
		
		private string _cli_domicilio;
		
		private string _cli_telefono;
		
		private string _cli_celular;
		
		private string _cli_apellido;
		
		private EntitySet<Factura> _Factura;
		
		private EntitySet<Ingreso> _Ingreso;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncli_cedulaChanging(string value);
    partial void Oncli_cedulaChanged();
    partial void Oncli_nombreChanging(string value);
    partial void Oncli_nombreChanged();
    partial void Oncli_domicilioChanging(string value);
    partial void Oncli_domicilioChanged();
    partial void Oncli_telefonoChanging(string value);
    partial void Oncli_telefonoChanged();
    partial void Oncli_celularChanging(string value);
    partial void Oncli_celularChanged();
    partial void Oncli_apellidoChanging(string value);
    partial void Oncli_apellidoChanged();
    #endregion
		
		public Cliente()
		{
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			this._Ingreso = new EntitySet<Ingreso>(new Action<Ingreso>(this.attach_Ingreso), new Action<Ingreso>(this.detach_Ingreso));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_cedula", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cli_cedula
		{
			get
			{
				return this._cli_cedula;
			}
			set
			{
				if ((this._cli_cedula != value))
				{
					this.Oncli_cedulaChanging(value);
					this.SendPropertyChanging();
					this._cli_cedula = value;
					this.SendPropertyChanged("cli_cedula");
					this.Oncli_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_nombre", DbType="VarChar(50)")]
		public string cli_nombre
		{
			get
			{
				return this._cli_nombre;
			}
			set
			{
				if ((this._cli_nombre != value))
				{
					this.Oncli_nombreChanging(value);
					this.SendPropertyChanging();
					this._cli_nombre = value;
					this.SendPropertyChanged("cli_nombre");
					this.Oncli_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_domicilio", DbType="VarChar(50)")]
		public string cli_domicilio
		{
			get
			{
				return this._cli_domicilio;
			}
			set
			{
				if ((this._cli_domicilio != value))
				{
					this.Oncli_domicilioChanging(value);
					this.SendPropertyChanging();
					this._cli_domicilio = value;
					this.SendPropertyChanged("cli_domicilio");
					this.Oncli_domicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_telefono", DbType="NChar(7)")]
		public string cli_telefono
		{
			get
			{
				return this._cli_telefono;
			}
			set
			{
				if ((this._cli_telefono != value))
				{
					this.Oncli_telefonoChanging(value);
					this.SendPropertyChanging();
					this._cli_telefono = value;
					this.SendPropertyChanged("cli_telefono");
					this.Oncli_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_celular", DbType="NChar(10)")]
		public string cli_celular
		{
			get
			{
				return this._cli_celular;
			}
			set
			{
				if ((this._cli_celular != value))
				{
					this.Oncli_celularChanging(value);
					this.SendPropertyChanging();
					this._cli_celular = value;
					this.SendPropertyChanged("cli_celular");
					this.Oncli_celularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_apellido", DbType="VarChar(50)")]
		public string cli_apellido
		{
			get
			{
				return this._cli_apellido;
			}
			set
			{
				if ((this._cli_apellido != value))
				{
					this.Oncli_apellidoChanging(value);
					this.SendPropertyChanging();
					this._cli_apellido = value;
					this.SendPropertyChanged("cli_apellido");
					this.Oncli_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Factura", ThisKey="cli_cedula", OtherKey="fac_ced_cliente")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Ingreso", Storage="_Ingreso", ThisKey="cli_cedula", OtherKey="ing_ced_cliente")]
		public EntitySet<Ingreso> Ingreso
		{
			get
			{
				return this._Ingreso;
			}
			set
			{
				this._Ingreso.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_producto")]
	public partial class Detalle_producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nfactura;
		
		private int _pro_codigo;
		
		private System.Nullable<int> _cantidad;
		
		private System.Nullable<decimal> _subtotal;
		
		private string _descripcion;
		
		private EntityRef<Factura> _Factura;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnfacturaChanging(int value);
    partial void OnnfacturaChanged();
    partial void Onpro_codigoChanging(int value);
    partial void Onpro_codigoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    partial void OnsubtotalChanging(System.Nullable<decimal> value);
    partial void OnsubtotalChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Detalle_producto()
		{
			this._Factura = default(EntityRef<Factura>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nfactura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nfactura
		{
			get
			{
				return this._nfactura;
			}
			set
			{
				if ((this._nfactura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnfacturaChanging(value);
					this.SendPropertyChanging();
					this._nfactura = value;
					this.SendPropertyChanged("nfactura");
					this.OnnfacturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle_producto", Storage="_Factura", ThisKey="nfactura", OtherKey="fac_n_factura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Detalle_producto.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Detalle_producto.Add(this);
						this._nfactura = value.fac_n_factura;
					}
					else
					{
						this._nfactura = default(int);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_producto", Storage="_Producto", ThisKey="pro_codigo", OtherKey="pro_codigo", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_producto.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_producto.Add(this);
						this._pro_codigo = value.pro_codigo;
					}
					else
					{
						this._pro_codigo = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Equipo")]
	public partial class Equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _equ_serie;
		
		private string _equ_modelo;
		
		private string _equ_tipo;
		
		private System.Nullable<short> _equ__n_ingresos;
		
		private System.Nullable<int> _equ_n_factura;
		
		private EntitySet<Ingreso> _Ingreso;
		
		private EntityRef<Factura_compra> _Factura_compra;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onequ_serieChanging(string value);
    partial void Onequ_serieChanged();
    partial void Onequ_modeloChanging(string value);
    partial void Onequ_modeloChanged();
    partial void Onequ_tipoChanging(string value);
    partial void Onequ_tipoChanged();
    partial void Onequ__n_ingresosChanging(System.Nullable<short> value);
    partial void Onequ__n_ingresosChanged();
    partial void Onequ_n_facturaChanging(System.Nullable<int> value);
    partial void Onequ_n_facturaChanged();
    #endregion
		
		public Equipo()
		{
			this._Ingreso = new EntitySet<Ingreso>(new Action<Ingreso>(this.attach_Ingreso), new Action<Ingreso>(this.detach_Ingreso));
			this._Factura_compra = default(EntityRef<Factura_compra>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equ_serie", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string equ_serie
		{
			get
			{
				return this._equ_serie;
			}
			set
			{
				if ((this._equ_serie != value))
				{
					this.Onequ_serieChanging(value);
					this.SendPropertyChanging();
					this._equ_serie = value;
					this.SendPropertyChanged("equ_serie");
					this.Onequ_serieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equ_modelo", DbType="VarChar(20)")]
		public string equ_modelo
		{
			get
			{
				return this._equ_modelo;
			}
			set
			{
				if ((this._equ_modelo != value))
				{
					this.Onequ_modeloChanging(value);
					this.SendPropertyChanging();
					this._equ_modelo = value;
					this.SendPropertyChanged("equ_modelo");
					this.Onequ_modeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equ_tipo", DbType="VarChar(20)")]
		public string equ_tipo
		{
			get
			{
				return this._equ_tipo;
			}
			set
			{
				if ((this._equ_tipo != value))
				{
					this.Onequ_tipoChanging(value);
					this.SendPropertyChanging();
					this._equ_tipo = value;
					this.SendPropertyChanged("equ_tipo");
					this.Onequ_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equ__n_ingresos", DbType="SmallInt")]
		public System.Nullable<short> equ__n_ingresos
		{
			get
			{
				return this._equ__n_ingresos;
			}
			set
			{
				if ((this._equ__n_ingresos != value))
				{
					this.Onequ__n_ingresosChanging(value);
					this.SendPropertyChanging();
					this._equ__n_ingresos = value;
					this.SendPropertyChanged("equ__n_ingresos");
					this.Onequ__n_ingresosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equ_n_factura", DbType="Int")]
		public System.Nullable<int> equ_n_factura
		{
			get
			{
				return this._equ_n_factura;
			}
			set
			{
				if ((this._equ_n_factura != value))
				{
					if (this._Factura_compra.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onequ_n_facturaChanging(value);
					this.SendPropertyChanging();
					this._equ_n_factura = value;
					this.SendPropertyChanged("equ_n_factura");
					this.Onequ_n_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Ingreso", Storage="_Ingreso", ThisKey="equ_serie", OtherKey="ing_serie_equipo")]
		public EntitySet<Ingreso> Ingreso
		{
			get
			{
				return this._Ingreso;
			}
			set
			{
				this._Ingreso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_compra_Equipo", Storage="_Factura_compra", ThisKey="equ_n_factura", OtherKey="fc_numero", IsForeignKey=true)]
		public Factura_compra Factura_compra
		{
			get
			{
				return this._Factura_compra.Entity;
			}
			set
			{
				Factura_compra previousValue = this._Factura_compra.Entity;
				if (((previousValue != value) 
							|| (this._Factura_compra.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura_compra.Entity = null;
						previousValue.Equipo.Remove(this);
					}
					this._Factura_compra.Entity = value;
					if ((value != null))
					{
						value.Equipo.Add(this);
						this._equ_n_factura = value.fc_numero;
					}
					else
					{
						this._equ_n_factura = default(Nullable<int>);
					}
					this.SendPropertyChanged("Factura_compra");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = this;
		}
		
		private void detach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura")]
	public partial class Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fac_n_factura;
		
		private System.Nullable<System.DateTime> _fac_fecha;
		
		private string _fac_ced_recep;
		
		private string _fac_ced_cliente;
		
		private System.Nullable<decimal> _fac_subtotal;
		
		private System.Nullable<decimal> _fac_iva;
		
		private System.Nullable<decimal> _fac_total;
		
		private System.Nullable<bool> _fac_anulada;
		
		private EntitySet<Detalle_producto> _Detalle_producto;
		
		private EntitySet<Ingreso> _Ingreso;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfac_n_facturaChanging(int value);
    partial void Onfac_n_facturaChanged();
    partial void Onfac_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfac_fechaChanged();
    partial void Onfac_ced_recepChanging(string value);
    partial void Onfac_ced_recepChanged();
    partial void Onfac_ced_clienteChanging(string value);
    partial void Onfac_ced_clienteChanged();
    partial void Onfac_subtotalChanging(System.Nullable<decimal> value);
    partial void Onfac_subtotalChanged();
    partial void Onfac_ivaChanging(System.Nullable<decimal> value);
    partial void Onfac_ivaChanged();
    partial void Onfac_totalChanging(System.Nullable<decimal> value);
    partial void Onfac_totalChanged();
    partial void Onfac_anuladaChanging(System.Nullable<bool> value);
    partial void Onfac_anuladaChanged();
    #endregion
		
		public Factura()
		{
			this._Detalle_producto = new EntitySet<Detalle_producto>(new Action<Detalle_producto>(this.attach_Detalle_producto), new Action<Detalle_producto>(this.detach_Detalle_producto));
			this._Ingreso = new EntitySet<Ingreso>(new Action<Ingreso>(this.attach_Ingreso), new Action<Ingreso>(this.detach_Ingreso));
			this._Cliente = default(EntityRef<Cliente>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_n_factura", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fac_n_factura
		{
			get
			{
				return this._fac_n_factura;
			}
			set
			{
				if ((this._fac_n_factura != value))
				{
					this.Onfac_n_facturaChanging(value);
					this.SendPropertyChanging();
					this._fac_n_factura = value;
					this.SendPropertyChanged("fac_n_factura");
					this.Onfac_n_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fac_fecha
		{
			get
			{
				return this._fac_fecha;
			}
			set
			{
				if ((this._fac_fecha != value))
				{
					this.Onfac_fechaChanging(value);
					this.SendPropertyChanging();
					this._fac_fecha = value;
					this.SendPropertyChanged("fac_fecha");
					this.Onfac_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_ced_recep", DbType="NChar(10)")]
		public string fac_ced_recep
		{
			get
			{
				return this._fac_ced_recep;
			}
			set
			{
				if ((this._fac_ced_recep != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfac_ced_recepChanging(value);
					this.SendPropertyChanging();
					this._fac_ced_recep = value;
					this.SendPropertyChanged("fac_ced_recep");
					this.Onfac_ced_recepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_ced_cliente", DbType="NChar(10)")]
		public string fac_ced_cliente
		{
			get
			{
				return this._fac_ced_cliente;
			}
			set
			{
				if ((this._fac_ced_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfac_ced_clienteChanging(value);
					this.SendPropertyChanging();
					this._fac_ced_cliente = value;
					this.SendPropertyChanged("fac_ced_cliente");
					this.Onfac_ced_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_subtotal", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> fac_subtotal
		{
			get
			{
				return this._fac_subtotal;
			}
			set
			{
				if ((this._fac_subtotal != value))
				{
					this.Onfac_subtotalChanging(value);
					this.SendPropertyChanging();
					this._fac_subtotal = value;
					this.SendPropertyChanged("fac_subtotal");
					this.Onfac_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_iva", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> fac_iva
		{
			get
			{
				return this._fac_iva;
			}
			set
			{
				if ((this._fac_iva != value))
				{
					this.Onfac_ivaChanging(value);
					this.SendPropertyChanging();
					this._fac_iva = value;
					this.SendPropertyChanged("fac_iva");
					this.Onfac_ivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_total", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> fac_total
		{
			get
			{
				return this._fac_total;
			}
			set
			{
				if ((this._fac_total != value))
				{
					this.Onfac_totalChanging(value);
					this.SendPropertyChanging();
					this._fac_total = value;
					this.SendPropertyChanged("fac_total");
					this.Onfac_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_anulada", DbType="Bit")]
		public System.Nullable<bool> fac_anulada
		{
			get
			{
				return this._fac_anulada;
			}
			set
			{
				if ((this._fac_anulada != value))
				{
					this.Onfac_anuladaChanging(value);
					this.SendPropertyChanging();
					this._fac_anulada = value;
					this.SendPropertyChanged("fac_anulada");
					this.Onfac_anuladaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Detalle_producto", Storage="_Detalle_producto", ThisKey="fac_n_factura", OtherKey="nfactura")]
		public EntitySet<Detalle_producto> Detalle_producto
		{
			get
			{
				return this._Detalle_producto;
			}
			set
			{
				this._Detalle_producto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Ingreso", Storage="_Ingreso", ThisKey="fac_n_factura", OtherKey="ing_n_factura")]
		public EntitySet<Ingreso> Ingreso
		{
			get
			{
				return this._Ingreso;
			}
			set
			{
				this._Ingreso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Factura", Storage="_Cliente", ThisKey="fac_ced_cliente", OtherKey="cli_cedula", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._fac_ced_cliente = value.cli_cedula;
					}
					else
					{
						this._fac_ced_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Usuario", ThisKey="fac_ced_recep", OtherKey="usu_cedula", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Factura.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Factura.Add(this);
						this._fac_ced_recep = value.usu_cedula;
					}
					else
					{
						this._fac_ced_recep = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_producto(Detalle_producto entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Detalle_producto(Detalle_producto entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
		
		private void attach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Factura = this;
		}
		
		private void detach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Factura = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura_compra")]
	public partial class Factura_compra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fc_numero;
		
		private System.Nullable<System.DateTime> _fc_fecha;
		
		private string _fc_cedula;
		
		private EntitySet<Equipo> _Equipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfc_numeroChanging(int value);
    partial void Onfc_numeroChanged();
    partial void Onfc_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfc_fechaChanged();
    partial void Onfc_cedulaChanging(string value);
    partial void Onfc_cedulaChanged();
    #endregion
		
		public Factura_compra()
		{
			this._Equipo = new EntitySet<Equipo>(new Action<Equipo>(this.attach_Equipo), new Action<Equipo>(this.detach_Equipo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_numero", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fc_numero
		{
			get
			{
				return this._fc_numero;
			}
			set
			{
				if ((this._fc_numero != value))
				{
					this.Onfc_numeroChanging(value);
					this.SendPropertyChanging();
					this._fc_numero = value;
					this.SendPropertyChanged("fc_numero");
					this.Onfc_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fc_fecha
		{
			get
			{
				return this._fc_fecha;
			}
			set
			{
				if ((this._fc_fecha != value))
				{
					this.Onfc_fechaChanging(value);
					this.SendPropertyChanging();
					this._fc_fecha = value;
					this.SendPropertyChanged("fc_fecha");
					this.Onfc_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fc_cedula", DbType="NChar(10)")]
		public string fc_cedula
		{
			get
			{
				return this._fc_cedula;
			}
			set
			{
				if ((this._fc_cedula != value))
				{
					this.Onfc_cedulaChanging(value);
					this.SendPropertyChanging();
					this._fc_cedula = value;
					this.SendPropertyChanged("fc_cedula");
					this.Onfc_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_compra_Equipo", Storage="_Equipo", ThisKey="fc_numero", OtherKey="equ_n_factura")]
		public EntitySet<Equipo> Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				this._Equipo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Equipo(Equipo entity)
		{
			this.SendPropertyChanging();
			entity.Factura_compra = this;
		}
		
		private void detach_Equipo(Equipo entity)
		{
			this.SendPropertyChanging();
			entity.Factura_compra = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ingreso")]
	public partial class Ingreso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ing_codigo;
		
		private System.Nullable<System.DateTime> _ing_fecha;
		
		private string _ing_problema;
		
		private string _ing_observaciones;
		
		private string _ing_accesorios;
		
		private string _ing_ced_cliente;
		
		private string _ing_serie_equipo;
		
		private System.Nullable<bool> _ing_garantía;
		
		private string _ing_estado;
		
		private string _ing_ced_recepcionista;
		
		private string _ing_ced_tecnico;
		
		private System.Nullable<int> _ing_n_factura;
		
		private System.Nullable<decimal> _ing_costo;
		
		private string _ing_diagnostico;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Equipo> _Equipo;
		
		private EntityRef<Factura> _Factura;
		
		private EntityRef<Usuario> _Usuario;
		
		private EntityRef<Usuario> _Usuario1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oning_codigoChanging(int value);
    partial void Oning_codigoChanged();
    partial void Oning_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Oning_fechaChanged();
    partial void Oning_problemaChanging(string value);
    partial void Oning_problemaChanged();
    partial void Oning_observacionesChanging(string value);
    partial void Oning_observacionesChanged();
    partial void Oning_accesoriosChanging(string value);
    partial void Oning_accesoriosChanged();
    partial void Oning_ced_clienteChanging(string value);
    partial void Oning_ced_clienteChanged();
    partial void Oning_serie_equipoChanging(string value);
    partial void Oning_serie_equipoChanged();
    partial void Oning_garantíaChanging(System.Nullable<bool> value);
    partial void Oning_garantíaChanged();
    partial void Oning_estadoChanging(string value);
    partial void Oning_estadoChanged();
    partial void Oning_ced_recepcionistaChanging(string value);
    partial void Oning_ced_recepcionistaChanged();
    partial void Oning_ced_tecnicoChanging(string value);
    partial void Oning_ced_tecnicoChanged();
    partial void Oning_n_facturaChanging(System.Nullable<int> value);
    partial void Oning_n_facturaChanged();
    partial void Oning_costoChanging(System.Nullable<decimal> value);
    partial void Oning_costoChanged();
    partial void Oning_diagnosticoChanging(string value);
    partial void Oning_diagnosticoChanged();
    #endregion
		
		public Ingreso()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Equipo = default(EntityRef<Equipo>);
			this._Factura = default(EntityRef<Factura>);
			this._Usuario = default(EntityRef<Usuario>);
			this._Usuario1 = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ing_codigo
		{
			get
			{
				return this._ing_codigo;
			}
			set
			{
				if ((this._ing_codigo != value))
				{
					this.Oning_codigoChanging(value);
					this.SendPropertyChanging();
					this._ing_codigo = value;
					this.SendPropertyChanged("ing_codigo");
					this.Oning_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> ing_fecha
		{
			get
			{
				return this._ing_fecha;
			}
			set
			{
				if ((this._ing_fecha != value))
				{
					this.Oning_fechaChanging(value);
					this.SendPropertyChanging();
					this._ing_fecha = value;
					this.SendPropertyChanged("ing_fecha");
					this.Oning_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_problema", DbType="VarChar(50)")]
		public string ing_problema
		{
			get
			{
				return this._ing_problema;
			}
			set
			{
				if ((this._ing_problema != value))
				{
					this.Oning_problemaChanging(value);
					this.SendPropertyChanging();
					this._ing_problema = value;
					this.SendPropertyChanged("ing_problema");
					this.Oning_problemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_observaciones", DbType="VarChar(50)")]
		public string ing_observaciones
		{
			get
			{
				return this._ing_observaciones;
			}
			set
			{
				if ((this._ing_observaciones != value))
				{
					this.Oning_observacionesChanging(value);
					this.SendPropertyChanging();
					this._ing_observaciones = value;
					this.SendPropertyChanged("ing_observaciones");
					this.Oning_observacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_accesorios", DbType="VarChar(30)")]
		public string ing_accesorios
		{
			get
			{
				return this._ing_accesorios;
			}
			set
			{
				if ((this._ing_accesorios != value))
				{
					this.Oning_accesoriosChanging(value);
					this.SendPropertyChanging();
					this._ing_accesorios = value;
					this.SendPropertyChanged("ing_accesorios");
					this.Oning_accesoriosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_ced_cliente", DbType="NChar(10)")]
		public string ing_ced_cliente
		{
			get
			{
				return this._ing_ced_cliente;
			}
			set
			{
				if ((this._ing_ced_cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oning_ced_clienteChanging(value);
					this.SendPropertyChanging();
					this._ing_ced_cliente = value;
					this.SendPropertyChanged("ing_ced_cliente");
					this.Oning_ced_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_serie_equipo", DbType="VarChar(20)")]
		public string ing_serie_equipo
		{
			get
			{
				return this._ing_serie_equipo;
			}
			set
			{
				if ((this._ing_serie_equipo != value))
				{
					if (this._Equipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oning_serie_equipoChanging(value);
					this.SendPropertyChanging();
					this._ing_serie_equipo = value;
					this.SendPropertyChanged("ing_serie_equipo");
					this.Oning_serie_equipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_garantía", DbType="Bit")]
		public System.Nullable<bool> ing_garantía
		{
			get
			{
				return this._ing_garantía;
			}
			set
			{
				if ((this._ing_garantía != value))
				{
					this.Oning_garantíaChanging(value);
					this.SendPropertyChanging();
					this._ing_garantía = value;
					this.SendPropertyChanged("ing_garantía");
					this.Oning_garantíaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_estado", DbType="VarChar(30)")]
		public string ing_estado
		{
			get
			{
				return this._ing_estado;
			}
			set
			{
				if ((this._ing_estado != value))
				{
					this.Oning_estadoChanging(value);
					this.SendPropertyChanging();
					this._ing_estado = value;
					this.SendPropertyChanged("ing_estado");
					this.Oning_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_ced_recepcionista", DbType="NChar(10)")]
		public string ing_ced_recepcionista
		{
			get
			{
				return this._ing_ced_recepcionista;
			}
			set
			{
				if ((this._ing_ced_recepcionista != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oning_ced_recepcionistaChanging(value);
					this.SendPropertyChanging();
					this._ing_ced_recepcionista = value;
					this.SendPropertyChanged("ing_ced_recepcionista");
					this.Oning_ced_recepcionistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_ced_tecnico", DbType="NChar(10)")]
		public string ing_ced_tecnico
		{
			get
			{
				return this._ing_ced_tecnico;
			}
			set
			{
				if ((this._ing_ced_tecnico != value))
				{
					if (this._Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oning_ced_tecnicoChanging(value);
					this.SendPropertyChanging();
					this._ing_ced_tecnico = value;
					this.SendPropertyChanged("ing_ced_tecnico");
					this.Oning_ced_tecnicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_n_factura", DbType="Int")]
		public System.Nullable<int> ing_n_factura
		{
			get
			{
				return this._ing_n_factura;
			}
			set
			{
				if ((this._ing_n_factura != value))
				{
					if (this._Factura.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oning_n_facturaChanging(value);
					this.SendPropertyChanging();
					this._ing_n_factura = value;
					this.SendPropertyChanged("ing_n_factura");
					this.Oning_n_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_costo", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> ing_costo
		{
			get
			{
				return this._ing_costo;
			}
			set
			{
				if ((this._ing_costo != value))
				{
					this.Oning_costoChanging(value);
					this.SendPropertyChanging();
					this._ing_costo = value;
					this.SendPropertyChanged("ing_costo");
					this.Oning_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ing_diagnostico", DbType="NVarChar(50)")]
		public string ing_diagnostico
		{
			get
			{
				return this._ing_diagnostico;
			}
			set
			{
				if ((this._ing_diagnostico != value))
				{
					this.Oning_diagnosticoChanging(value);
					this.SendPropertyChanging();
					this._ing_diagnostico = value;
					this.SendPropertyChanged("ing_diagnostico");
					this.Oning_diagnosticoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Ingreso", Storage="_Cliente", ThisKey="ing_ced_cliente", OtherKey="cli_cedula", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Ingreso.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Ingreso.Add(this);
						this._ing_ced_cliente = value.cli_cedula;
					}
					else
					{
						this._ing_ced_cliente = default(string);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Ingreso", Storage="_Equipo", ThisKey="ing_serie_equipo", OtherKey="equ_serie", IsForeignKey=true)]
		public Equipo Equipo
		{
			get
			{
				return this._Equipo.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo.Entity;
				if (((previousValue != value) 
							|| (this._Equipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo.Entity = null;
						previousValue.Ingreso.Remove(this);
					}
					this._Equipo.Entity = value;
					if ((value != null))
					{
						value.Ingreso.Add(this);
						this._ing_serie_equipo = value.equ_serie;
					}
					else
					{
						this._ing_serie_equipo = default(string);
					}
					this.SendPropertyChanged("Equipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Ingreso", Storage="_Factura", ThisKey="ing_n_factura", OtherKey="fac_n_factura", IsForeignKey=true)]
		public Factura Factura
		{
			get
			{
				return this._Factura.Entity;
			}
			set
			{
				Factura previousValue = this._Factura.Entity;
				if (((previousValue != value) 
							|| (this._Factura.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura.Entity = null;
						previousValue.Ingreso.Remove(this);
					}
					this._Factura.Entity = value;
					if ((value != null))
					{
						value.Ingreso.Add(this);
						this._ing_n_factura = value.fac_n_factura;
					}
					else
					{
						this._ing_n_factura = default(Nullable<int>);
					}
					this.SendPropertyChanged("Factura");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ingreso", Storage="_Usuario", ThisKey="ing_ced_recepcionista", OtherKey="usu_cedula", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Ingreso.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Ingreso.Add(this);
						this._ing_ced_recepcionista = value.usu_cedula;
					}
					else
					{
						this._ing_ced_recepcionista = default(string);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ingreso1", Storage="_Usuario1", ThisKey="ing_ced_tecnico", OtherKey="usu_cedula", IsForeignKey=true)]
		public Usuario Usuario1
		{
			get
			{
				return this._Usuario1.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario1.Entity = null;
						previousValue.Ingreso1.Remove(this);
					}
					this._Usuario1.Entity = value;
					if ((value != null))
					{
						value.Ingreso1.Add(this);
						this._ing_ced_tecnico = value.usu_cedula;
					}
					else
					{
						this._ing_ced_tecnico = default(string);
					}
					this.SendPropertyChanged("Usuario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pieza")]
	public partial class Pieza : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pie_codigo;
		
		private string _pie_modelo;
		
		private string _pie_tipo;
		
		private System.Nullable<decimal> _pie_costo;
		
		private System.Nullable<int> _pie_cantidad;
		
		private System.Nullable<bool> _pie_baja;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpie_codigoChanging(int value);
    partial void Onpie_codigoChanged();
    partial void Onpie_modeloChanging(string value);
    partial void Onpie_modeloChanged();
    partial void Onpie_tipoChanging(string value);
    partial void Onpie_tipoChanged();
    partial void Onpie_costoChanging(System.Nullable<decimal> value);
    partial void Onpie_costoChanged();
    partial void Onpie_cantidadChanging(System.Nullable<int> value);
    partial void Onpie_cantidadChanged();
    partial void Onpie_bajaChanging(System.Nullable<bool> value);
    partial void Onpie_bajaChanged();
    #endregion
		
		public Pieza()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pie_codigo
		{
			get
			{
				return this._pie_codigo;
			}
			set
			{
				if ((this._pie_codigo != value))
				{
					this.Onpie_codigoChanging(value);
					this.SendPropertyChanging();
					this._pie_codigo = value;
					this.SendPropertyChanged("pie_codigo");
					this.Onpie_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_modelo", DbType="VarChar(20)")]
		public string pie_modelo
		{
			get
			{
				return this._pie_modelo;
			}
			set
			{
				if ((this._pie_modelo != value))
				{
					this.Onpie_modeloChanging(value);
					this.SendPropertyChanging();
					this._pie_modelo = value;
					this.SendPropertyChanged("pie_modelo");
					this.Onpie_modeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_tipo", DbType="VarChar(30)")]
		public string pie_tipo
		{
			get
			{
				return this._pie_tipo;
			}
			set
			{
				if ((this._pie_tipo != value))
				{
					this.Onpie_tipoChanging(value);
					this.SendPropertyChanging();
					this._pie_tipo = value;
					this.SendPropertyChanged("pie_tipo");
					this.Onpie_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_costo", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> pie_costo
		{
			get
			{
				return this._pie_costo;
			}
			set
			{
				if ((this._pie_costo != value))
				{
					this.Onpie_costoChanging(value);
					this.SendPropertyChanging();
					this._pie_costo = value;
					this.SendPropertyChanged("pie_costo");
					this.Onpie_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_cantidad", DbType="Int")]
		public System.Nullable<int> pie_cantidad
		{
			get
			{
				return this._pie_cantidad;
			}
			set
			{
				if ((this._pie_cantidad != value))
				{
					this.Onpie_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pie_cantidad = value;
					this.SendPropertyChanged("pie_cantidad");
					this.Onpie_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pie_baja", DbType="Bit")]
		public System.Nullable<bool> pie_baja
		{
			get
			{
				return this._pie_baja;
			}
			set
			{
				if ((this._pie_baja != value))
				{
					this.Onpie_bajaChanging(value);
					this.SendPropertyChanging();
					this._pie_baja = value;
					this.SendPropertyChanged("pie_baja");
					this.Onpie_bajaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pieza_usada")]
	public partial class Pieza_usada
	{
		
		private System.Nullable<int> _codigo_pieza;
		
		private System.Nullable<int> _codigo_ingreso;
		
		private string _serie;
		
		public Pieza_usada()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_pieza", DbType="Int")]
		public System.Nullable<int> codigo_pieza
		{
			get
			{
				return this._codigo_pieza;
			}
			set
			{
				if ((this._codigo_pieza != value))
				{
					this._codigo_pieza = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ingreso", DbType="Int")]
		public System.Nullable<int> codigo_ingreso
		{
			get
			{
				return this._codigo_ingreso;
			}
			set
			{
				if ((this._codigo_ingreso != value))
				{
					this._codigo_ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serie", DbType="VarChar(20)")]
		public string serie
		{
			get
			{
				return this._serie;
			}
			set
			{
				if ((this._serie != value))
				{
					this._serie = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_codigo;
		
		private string _pro_tipo;
		
		private string _pro_modelo;
		
		private System.Nullable<decimal> _pro_costo;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<bool> _pro_baja;
		
		private EntitySet<Detalle_producto> _Detalle_producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_codigoChanging(int value);
    partial void Onpro_codigoChanged();
    partial void Onpro_tipoChanging(string value);
    partial void Onpro_tipoChanged();
    partial void Onpro_modeloChanging(string value);
    partial void Onpro_modeloChanged();
    partial void Onpro_costoChanging(System.Nullable<decimal> value);
    partial void Onpro_costoChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_bajaChanging(System.Nullable<bool> value);
    partial void Onpro_bajaChanged();
    #endregion
		
		public Producto()
		{
			this._Detalle_producto = new EntitySet<Detalle_producto>(new Action<Detalle_producto>(this.attach_Detalle_producto), new Action<Detalle_producto>(this.detach_Detalle_producto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_tipo", DbType="VarChar(30)")]
		public string pro_tipo
		{
			get
			{
				return this._pro_tipo;
			}
			set
			{
				if ((this._pro_tipo != value))
				{
					this.Onpro_tipoChanging(value);
					this.SendPropertyChanging();
					this._pro_tipo = value;
					this.SendPropertyChanged("pro_tipo");
					this.Onpro_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_modelo", DbType="VarChar(15)")]
		public string pro_modelo
		{
			get
			{
				return this._pro_modelo;
			}
			set
			{
				if ((this._pro_modelo != value))
				{
					this.Onpro_modeloChanging(value);
					this.SendPropertyChanging();
					this._pro_modelo = value;
					this.SendPropertyChanged("pro_modelo");
					this.Onpro_modeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_costo", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> pro_costo
		{
			get
			{
				return this._pro_costo;
			}
			set
			{
				if ((this._pro_costo != value))
				{
					this.Onpro_costoChanging(value);
					this.SendPropertyChanging();
					this._pro_costo = value;
					this.SendPropertyChanged("pro_costo");
					this.Onpro_costoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_baja", DbType="Bit")]
		public System.Nullable<bool> pro_baja
		{
			get
			{
				return this._pro_baja;
			}
			set
			{
				if ((this._pro_baja != value))
				{
					this.Onpro_bajaChanging(value);
					this.SendPropertyChanging();
					this._pro_baja = value;
					this.SendPropertyChanged("pro_baja");
					this.Onpro_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_producto", Storage="_Detalle_producto", ThisKey="pro_codigo", OtherKey="pro_codigo")]
		public EntitySet<Detalle_producto> Detalle_producto
		{
			get
			{
				return this._Detalle_producto;
			}
			set
			{
				this._Detalle_producto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_producto(Detalle_producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_producto(Detalle_producto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trabajo")]
	public partial class Trabajo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tra_codigo;
		
		private string _tra_descripcion;
		
		private System.Nullable<decimal> _tra_costo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontra_codigoChanging(int value);
    partial void Ontra_codigoChanged();
    partial void Ontra_descripcionChanging(string value);
    partial void Ontra_descripcionChanged();
    partial void Ontra_costoChanging(System.Nullable<decimal> value);
    partial void Ontra_costoChanged();
    #endregion
		
		public Trabajo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tra_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tra_codigo
		{
			get
			{
				return this._tra_codigo;
			}
			set
			{
				if ((this._tra_codigo != value))
				{
					this.Ontra_codigoChanging(value);
					this.SendPropertyChanging();
					this._tra_codigo = value;
					this.SendPropertyChanged("tra_codigo");
					this.Ontra_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tra_descripcion", DbType="VarChar(50)")]
		public string tra_descripcion
		{
			get
			{
				return this._tra_descripcion;
			}
			set
			{
				if ((this._tra_descripcion != value))
				{
					this.Ontra_descripcionChanging(value);
					this.SendPropertyChanging();
					this._tra_descripcion = value;
					this.SendPropertyChanged("tra_descripcion");
					this.Ontra_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tra_costo", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> tra_costo
		{
			get
			{
				return this._tra_costo;
			}
			set
			{
				if ((this._tra_costo != value))
				{
					this.Ontra_costoChanging(value);
					this.SendPropertyChanging();
					this._tra_costo = value;
					this.SendPropertyChanged("tra_costo");
					this.Ontra_costoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trabajo_realizado")]
	public partial class Trabajo_realizado
	{
		
		private System.Nullable<int> _codigo_trabajo;
		
		private System.Nullable<int> _codigo_ingreso;
		
		public Trabajo_realizado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_trabajo", DbType="Int")]
		public System.Nullable<int> codigo_trabajo
		{
			get
			{
				return this._codigo_trabajo;
			}
			set
			{
				if ((this._codigo_trabajo != value))
				{
					this._codigo_trabajo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ingreso", DbType="Int")]
		public System.Nullable<int> codigo_ingreso
		{
			get
			{
				return this._codigo_ingreso;
			}
			set
			{
				if ((this._codigo_ingreso != value))
				{
					this._codigo_ingreso = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usu_cedula;
		
		private string _usu_nombre;
		
		private string _usu_domicilio;
		
		private string _usu_telefono;
		
		private string _usu_contrasenia;
		
		private string _usu_tipo;
		
		private string _usu_apellido;
		
		private System.Nullable<bool> _usu_baja;
		
		private EntitySet<Factura> _Factura;
		
		private EntitySet<Ingreso> _Ingreso;
		
		private EntitySet<Ingreso> _Ingreso1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_cedulaChanging(string value);
    partial void Onusu_cedulaChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_domicilioChanging(string value);
    partial void Onusu_domicilioChanged();
    partial void Onusu_telefonoChanging(string value);
    partial void Onusu_telefonoChanged();
    partial void Onusu_contraseniaChanging(string value);
    partial void Onusu_contraseniaChanged();
    partial void Onusu_tipoChanging(string value);
    partial void Onusu_tipoChanged();
    partial void Onusu_apellidoChanging(string value);
    partial void Onusu_apellidoChanged();
    partial void Onusu_bajaChanging(System.Nullable<bool> value);
    partial void Onusu_bajaChanged();
    #endregion
		
		public Usuario()
		{
			this._Factura = new EntitySet<Factura>(new Action<Factura>(this.attach_Factura), new Action<Factura>(this.detach_Factura));
			this._Ingreso = new EntitySet<Ingreso>(new Action<Ingreso>(this.attach_Ingreso), new Action<Ingreso>(this.detach_Ingreso));
			this._Ingreso1 = new EntitySet<Ingreso>(new Action<Ingreso>(this.attach_Ingreso1), new Action<Ingreso>(this.detach_Ingreso1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_cedula", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string usu_cedula
		{
			get
			{
				return this._usu_cedula;
			}
			set
			{
				if ((this._usu_cedula != value))
				{
					this.Onusu_cedulaChanging(value);
					this.SendPropertyChanging();
					this._usu_cedula = value;
					this.SendPropertyChanged("usu_cedula");
					this.Onusu_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(50)")]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_domicilio", DbType="VarChar(50)")]
		public string usu_domicilio
		{
			get
			{
				return this._usu_domicilio;
			}
			set
			{
				if ((this._usu_domicilio != value))
				{
					this.Onusu_domicilioChanging(value);
					this.SendPropertyChanging();
					this._usu_domicilio = value;
					this.SendPropertyChanged("usu_domicilio");
					this.Onusu_domicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_telefono", DbType="NChar(10)")]
		public string usu_telefono
		{
			get
			{
				return this._usu_telefono;
			}
			set
			{
				if ((this._usu_telefono != value))
				{
					this.Onusu_telefonoChanging(value);
					this.SendPropertyChanging();
					this._usu_telefono = value;
					this.SendPropertyChanged("usu_telefono");
					this.Onusu_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contrasenia", DbType="VarChar(20)")]
		public string usu_contrasenia
		{
			get
			{
				return this._usu_contrasenia;
			}
			set
			{
				if ((this._usu_contrasenia != value))
				{
					this.Onusu_contraseniaChanging(value);
					this.SendPropertyChanging();
					this._usu_contrasenia = value;
					this.SendPropertyChanged("usu_contrasenia");
					this.Onusu_contraseniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_tipo", DbType="NChar(15)")]
		public string usu_tipo
		{
			get
			{
				return this._usu_tipo;
			}
			set
			{
				if ((this._usu_tipo != value))
				{
					this.Onusu_tipoChanging(value);
					this.SendPropertyChanging();
					this._usu_tipo = value;
					this.SendPropertyChanged("usu_tipo");
					this.Onusu_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_apellido", DbType="VarChar(50)")]
		public string usu_apellido
		{
			get
			{
				return this._usu_apellido;
			}
			set
			{
				if ((this._usu_apellido != value))
				{
					this.Onusu_apellidoChanging(value);
					this.SendPropertyChanging();
					this._usu_apellido = value;
					this.SendPropertyChanged("usu_apellido");
					this.Onusu_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_baja", DbType="Bit")]
		public System.Nullable<bool> usu_baja
		{
			get
			{
				return this._usu_baja;
			}
			set
			{
				if ((this._usu_baja != value))
				{
					this.Onusu_bajaChanging(value);
					this.SendPropertyChanging();
					this._usu_baja = value;
					this.SendPropertyChanged("usu_baja");
					this.Onusu_bajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Factura", Storage="_Factura", ThisKey="usu_cedula", OtherKey="fac_ced_recep")]
		public EntitySet<Factura> Factura
		{
			get
			{
				return this._Factura;
			}
			set
			{
				this._Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ingreso", Storage="_Ingreso", ThisKey="usu_cedula", OtherKey="ing_ced_recepcionista")]
		public EntitySet<Ingreso> Ingreso
		{
			get
			{
				return this._Ingreso;
			}
			set
			{
				this._Ingreso.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Ingreso1", Storage="_Ingreso1", ThisKey="usu_cedula", OtherKey="ing_ced_tecnico")]
		public EntitySet<Ingreso> Ingreso1
		{
			get
			{
				return this._Ingreso1;
			}
			set
			{
				this._Ingreso1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Factura(Factura entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Ingreso(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Ingreso1(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Usuario1 = this;
		}
		
		private void detach_Ingreso1(Ingreso entity)
		{
			this.SendPropertyChanging();
			entity.Usuario1 = null;
		}
	}
}
#pragma warning restore 1591
